export default {
    APP_LOGIN:'APP_LOGIN',
    APP_MESSAGE:'APP_MESSAGE',

    FACE_VIDEO:'FACE_VIDEO',

    SYSTEM_INIT:'SYSTEM_INIT',
    SYSTEM_EDITOR:'SYSTEM_EDITOR',
    SYSTEM_ADDOR:'SYSTEM_ADDOR',
    SYSTEM_DELOR:'SYSTEM_DELOR',

    SYSTEM_DE_INIT:'SYSTEM_DE_INIT',
    SYSTEM_DE_ADDOR:'SYSTEM_DE_ADDOR',
    SYSTEM_DE_EDITOR:'SYSTEM_DE_EDITOR',
    SYSTEM_DE_DELOR:'SYSTEM_DE_DELOR',

    SYSTEM_USER_INIT:'SYSTEM_USER_INIT',
    SYSTEM_USER_ADDOR:'SYSTEM_USER_ADDOR',
    SYSTEM_USER_EDITOR:'SYSTEM_USER_EDITOR',
    SYSTEM_USER_DELOR:'SYSTEM_USER_DELOR',
    

    DEVICE_AREACAMERA_INIT:'DEVICE_AREACAMERA_INIT',
    DEVICE_AREACAMERA_INITALL:'DEVICE_AREACAMERA_INITALL',
    DEVICE_AREACAMERA_SELECTOR:'DEVICE_AREACAMERA_SELECTOR',
    DEVICE_AREACAMERA_DELOR:'DEVICE_AREACAMERA_DELOR',
    DEVICE_AREACAMERA_DELORS:'DEVICE_AREACAMERA_DELORS',
    DEVICE_AREACAMERA_ADDOR:'DEVICE_AREACAMERA_ADDOR',
    DEVICE_AREACAMERA_EDITOR:'DEVICE_AREACAMERA_EDITOR',
    DEVICE_AREACAMERA_STATUS:'DEVICE_AREACAMERA_STATUS',

    DEVICE_DEVICECAMERA_INIT:'DEVICE_DEVICECAMERA_INIT',
    DEVICE_DEVICECAMERA_SELECTOR:'DEVICE_DEVICECAMERA_SELECTOR',
    DEVICE_DEVICECAMERA_DELOR:'DEVICE_DEVICECAMERA_DELOR',
    DEVICE_DEVICECAMERA_DELORS:'DEVICE_DEVICECAMERA_DELORS',
    DEVICE_DEVICECAMERA_ADDOR:'DEVICE_DEVICECAMERA_ADDOR',
    DEVICE_DEVICECAMERA_EDITOR:'DEVICE_DEVICECAMERA_EDITOR',
    DEVICE_DEVICECAMERA_STATUS:'DEVICE_DEVICECAMERA_STATUS',
    DEVICE_DEVICECAMERA_SET:'DEVICE_DEVICECAMERA_SET',
    DEVICE_SERVER_INITALL:'DEVICE_SERVER_INITALL',
    DEVICE_DEVICECAMERA_INITALL:'DEVICE_DEVICECAMERA_INITALL',

    DEVICE_SERVER_INIT:'DEVICE_SERVER_INIT',
    DEVICE_SERVER_INITALL:'DEVICE_SERVER_INITALL',
    DEVICE_SERVER_SELECTOR:'DEVICE_SERVER_SELECTOR',
    DEVICE_SERVER_DELOR:'DEVICE_SERVER_DELOR',
    DEVICE_SERVER_ADDOR:'DEVICE_SERVER_ADDOR',
    DEVICE_SERVER_EDITOR:'DEVICE_SERVER_EDITOR',
    DEVICE_SERVER_STATUS:'DEVICE_SERVER_STATUS',


    DEVICE_STATUS_INIT:'DEVICE_STATUS_INIT',


    DEPLOY_SETUP_INIT:'DEPLOY_SETUP_INIT',
    DEPLOY_SETUP_SELECTOR:'DEPLOY_SETUP_SELECTOR',
    DEPLOY_SETUP_ADDOR:'DEPLOY_SETUP_ADDOR',
    DEPLOY_SETUP_DELOR:'DEPLOY_SETUP_DELOR',
    DEPLOY_SETUP_EDITOR:'DEPLOY_SETUP_EDITOR',

    DEPLOY_POLICE_INIT:'DEPLOY_POLICE_INIT',
    DEPLOY_POLICE_INITALL:'DEPLOY_POLICE_INITALL',
    DEPLOY_POLICE_SELECTOR:'DEPLOY_POLICE_SELECTOR',
    DEPLOY_POLICE_ADDOR:'DEPLOY_POLICE_ADDOR',
    DEPLOY_POLICE_DELOR:'DEPLOY_POLICE_DELOR',
    DEPLOY_POLICE_EDITOR:'DEPLOY_POLICE_EDITOR',


    DEPLOY_WARNING_INIT:'DEPLOY_WARNING_INIT',
    DEPLOY_PEOPLESE_ADD:'DEPLOY_PEOPLESE_ADD',



    DEPLOY_PEOPLESE_INIT:'DEPLOY_PEOPLESE_INIT',
    DEPLOY_PEOPLESE_ADD:'DEPLOY_PEOPLESE_ADD',
    DEPLOY_PEOPLESE_EDIT:'DEPLOY_PEOPLESE_EDIT',
    DEPLOY_PEOPLESE_REMOVE:'DEPLOY_PEOPLESE_REMOVE',


    LOGIN_IN :'LOGIN_IN',
    LOGIN_OUT : 'LOGIN_OUT',


    WARNING_ADDOR:'WARNING_ADDOR',


    DEVICE_FACE_INITALL:'DEVICE_FACE_INITALL',
    DEVICE_FACE_ADDOR:'DEVICE_FACE_ADDOR',
    DELETE_FACE_ADDOR:'DELETE_FACE_ADDOR',


    DEVICE_CONTROL_INITALL:'DEVICE_CONTROL_INITALL',
    DEPLOY_WARNING_ADDOR:'DEPLOY_WARNING_ADDOR',
    DEPLOY_WARNING_EDITOR:'DEPLOY_WARNING_EDITOR',
    DEPLOY_WARNING_DELETE:'DEPLOY_WARNING_DELETE'
    
    
};






















